#!/usr/bin/env python3
"""Patch: add per-mode panels to Ábra 1 (corr matrix) and Ábra 4 (state consistency)"""
import sys

with open('metric_collection_per_junction.py', 'rb') as f:
    raw = f.read()

changes = []

# ─────────────────────────────────────────────────────────────────────────────
# Ábra 1: reward_correlation_matrix.png  → per-mode side-by-side panels
# ─────────────────────────────────────────────────────────────────────────────
old1 = (
    b"    # \xc3\x81bra 1: Korrel\xc3\xa1ci\xc3\xb3 m\xc3\xa1trix \xe2\x80\x94 csak egyedi (nem aggreg\xc3\xa1lt) metrik\xc3\xa1k\r\n"
    b"    # Kisz\xc5\xb1rj\xc3\xbck a reward_* \xc3\xa9s triplet_* aggreg\xc3\xa1lt oszlopokat, csak nyers v\xc3\xa1ltoz\xc3\xb3kat mutatunk\r\n"
    b"    plot_metrics = [m for m in candidate_metrics\r\n"
    b"                    if not m.startswith('reward_') and not m.startswith('triplet_')]\r\n"
    b"    plot_corr = corr_matrix.loc[plot_metrics, plot_metrics]\r\n"
    b"    n_met = len(plot_metrics)\r\n"
    b"    fig_sz = max(8, n_met * 1.2)\r\n"
    b"    fig, ax = plt.subplots(figsize=(fig_sz, fig_sz * 0.85))\r\n"
    b"    im = ax.imshow(plot_corr.values, cmap='RdBu_r', vmin=-1, vmax=1, aspect='auto')\r\n"
    b"    ax.set_xticks(range(n_met))\r\n"
    b"    ax.set_xticklabels(plot_metrics, rotation=45, ha='right', fontsize=9)\r\n"
    b"    ax.set_yticks(range(n_met))\r\n"
    b"    ax.set_yticklabels(plot_metrics, fontsize=9)\r\n"
    b"    for i in range(n_met):\r\n"
    b"        for j in range(n_met):\r\n"
    b"            val = plot_corr.values[i, j]\r\n"
    b"            color = 'white' if abs(val) > 0.6 else 'black'\r\n"
    b"            weight = 'bold' if abs(val) > 0.85 and i != j else 'normal'\r\n"
    b"            ax.text(j, i, f'{val:.2f}', ha='center', va='center',\r\n"
    b"                    fontsize=8, color=color, fontweight=weight)\r\n"
    b"    fig.colorbar(im, ax=ax, shrink=0.8)\r\n"
    b"    ax.set_title('Metric Correlation Matrix (log-transformed)\\n* Bold = redundant (|r| > 0.85)', fontsize=13)\r\n"
    b"    plt.tight_layout()\r\n"
    b"    fig.savefig(os.path.join(output_dir, 'reward_correlation_matrix.png'), dpi=200)\r\n"
    b"    plt.close()\r\n"
    b"    print(f\"\\n  reward_correlation_matrix.png mentve ({n_met} egyedi metrika, aggreg\xc3\xa1lt kisz\xc5\xb1rve)\")\r\n"
)
new1 = (
    b"    # \xc3\x81bra 1: Korrel\xc3\xa1ci\xc3\xb3 m\xc3\xa1trix \xe2\x80\x94 m\xc3\xb3dok szerint bontva (random / mixed / actuated)\r\n"
    b"    plot_metrics = [m for m in candidate_metrics\r\n"
    b"                    if not m.startswith('reward_') and not m.startswith('triplet_')]\r\n"
    b"    n_met = len(plot_metrics)\r\n"
    b"    _mc_order  = ['random', 'mixed', 'actuated']\r\n"
    b"    _mc_colors = {'random': '#e74c3c', 'mixed': '#f39c12', 'actuated': '#2980b9'}\r\n"
    b"    _mc_titles = {'random': 'Random (\xcf\xb5=1.0)', 'mixed': f'Mixed (\xcf\xb5={MIXED_EPSILON})', 'actuated': 'Actuated (\xcf\xb5=0.0)'}\r\n"
    b"    def _mg_c(cm): return 'actuated' if cm == 'actuated' else ('mixed' if str(cm).startswith('mixed') else 'random')\r\n"
    b"    if 'mode_group' not in df_valid.columns:\r\n"
    b"        df_valid['mode_group'] = df_valid['control_mode'].apply(_mg_c)\r\n"
    b"    present_mc = [m for m in _mc_order if m in df_valid['mode_group'].values]\r\n"
    b"    n_mc = max(len(present_mc), 1)\r\n"
    b"    fig_sq = max(8, n_met * 1.1)\r\n"
    b"    fig, axes_mc = plt.subplots(1, n_mc, figsize=(fig_sq * n_mc, fig_sq * 0.88))\r\n"
    b"    if n_mc == 1:\r\n"
    b"        axes_mc = [axes_mc]\r\n"
    b"    for ax_mc, mg_mc in zip(axes_mc, present_mc):\r\n"
    b"        sub_mc = df_valid[df_valid['mode_group'] == mg_mc]\r\n"
    b"        cd_mc = {}\r\n"
    b"        for col in plot_metrics:\r\n"
    b"            if col in sub_mc.columns:\r\n"
    b"                v = sub_mc[col].values\r\n"
    b"                if len(v[v > 0]) > 5:\r\n"
    b"                    cd_mc[col] = np.log(np.clip(v, epsilon, None) + epsilon)\r\n"
    b"        cd_cols_mc = [c for c in plot_metrics if c in cd_mc]\r\n"
    b"        if cd_cols_mc:\r\n"
    b"            cm_sub = pd.DataFrame({c: cd_mc[c] for c in cd_cols_mc}).corr(method='pearson')\r\n"
    b"            vals_mc = cm_sub.values\r\n"
    b"        else:\r\n"
    b"            cd_cols_mc = plot_metrics[:1] if plot_metrics else []\r\n"
    b"            vals_mc = np.eye(len(cd_cols_mc))\r\n"
    b"        n_c = len(cd_cols_mc)\r\n"
    b"        im = ax_mc.imshow(vals_mc, cmap='RdBu_r', vmin=-1, vmax=1, aspect='auto')\r\n"
    b"        ax_mc.set_xticks(range(n_c))\r\n"
    b"        ax_mc.set_xticklabels(cd_cols_mc, rotation=45, ha='right', fontsize=8)\r\n"
    b"        ax_mc.set_yticks(range(n_c))\r\n"
    b"        ax_mc.set_yticklabels(cd_cols_mc, fontsize=8)\r\n"
    b"        for i in range(n_c):\r\n"
    b"            for j in range(n_c):\r\n"
    b"                val = vals_mc[i, j]\r\n"
    b"                col_t = 'white' if abs(val) > 0.6 else 'black'\r\n"
    b"                w = 'bold' if abs(val) > 0.85 and i != j else 'normal'\r\n"
    b"                ax_mc.text(j, i, f'{val:.2f}', ha='center', va='center',\r\n"
    b"                           fontsize=7, color=col_t, fontweight=w)\r\n"
    b"        fig.colorbar(im, ax=ax_mc, shrink=0.75)\r\n"
    b"        ax_mc.set_title(\r\n"
    b"            f'{_mc_titles.get(mg_mc, mg_mc)}  (n={len(sub_mc)})'\r\n"
    b"            f'\\nMetric Correlation Matrix  |  bold = redundant (|r|>0.85)',\r\n"
    b"            fontsize=10, color=_mc_colors.get(mg_mc, 'black'), fontweight='bold')\r\n"
    b"    fig.suptitle('Metric Correlation Matrix (log-transformed)  |  per Control Mode',\r\n"
    b"                 fontsize=13, y=1.02)\r\n"
    b"    plt.tight_layout()\r\n"
    b"    fig.savefig(os.path.join(output_dir, 'reward_correlation_matrix.png'), dpi=200, bbox_inches='tight')\r\n"
    b"    plt.close()\r\n"
    b"    print(f\"\\n  reward_correlation_matrix.png mentve ({n_met} egyedi metrika, {n_mc} m\xc3\xb3d)\")\r\n"
)
if old1 in raw:
    raw = raw.replace(old1, new1, 1); changes.append("Ábra1:OK")
elif b"per Control Mode" in raw:
    changes.append("Ábra1:SKIP")
else:
    sys.exit("FAIL Ábra1")

# ─────────────────────────────────────────────────────────────────────────────
# Ábra 4: reward_state_consistency.png  → n_modes rows (heatmap + MI per mode)
# ─────────────────────────────────────────────────────────────────────────────
old4 = (
    b"    _plot_jid = 'R1C1_C'\r\n"
    b"    _plot_sc  = agg_state_cols  # csak az 5 aggreg\xc3\xa1lt\r\n"
    b"    _plot_df  = df_valid[df_valid['junction'] == _plot_jid].copy() if 'junction' in df_valid.columns else df_valid\r\n"
    b"    if has_det_data and len(_plot_df) > 0:\r\n"
    b"        # Nyers metrik\xc3\xa1k (a ranglista komb\xc3\xb3it ezek alkotj\xc3\xa1k) + normaliz\xc3\xa1lt reward jel\xc3\xb6ltek\r\n"
    b"        raw_metrics = [m for m in ['TotalWaitingTime', 'TotalCO2', 'QueueLength',\r\n"
    b"                                    'TotalTravelTime', 'HaltRatio', 'SpeedStd', 'AvgOccupancy']\r\n"
    b"                       if m in _plot_df.columns]\r\n"
    b"        reward_metrics_to_test = raw_metrics + reward_metrics_5\r\n"
    b"        n_rewards = len(reward_metrics_to_test)\r\n"
    b"        n_states  = len(_plot_sc)\r\n"
    b"        fig, axes = plt.subplots(1, 2, figsize=(14, max(4, n_rewards * 0.9)),\r\n"
    b"                                 gridspec_kw={'width_ratios': [1.2, 1]})\r\n"
    b"\r\n"
    b"        # 4a. Heatmap\r\n"
    b"        ax = axes[0]\r\n"
    b"        sr_matrix = []\r\n"
    b"        for rm in reward_metrics_to_test:\r\n"
    b"            row_vals = []\r\n"
    b"            for sc in _plot_sc:\r\n"
    b"                sub = _plot_df[[sc, rm]].dropna() if rm in _plot_df.columns else pd.DataFrame()\r\n"
    b"                sub = sub[(sub[sc] != 0) | (sub[rm] != 0)] if len(sub) > 0 else sub\r\n"
    b"                if len(sub) > 30:\r\n"
    b"                    r, _ = stats.pearsonr(sub[sc].values, sub[rm].values)\r\n"
    b"                    row_vals.append(r)\r\n"
    b"                else:\r\n"
    b"                    row_vals.append(0.0)\r\n"
    b"            sr_matrix.append(row_vals)\r\n"
    b"        sr_matrix = np.array(sr_matrix)\r\n"
    b"        im = ax.imshow(sr_matrix, cmap='RdBu_r', vmin=-1, vmax=1, aspect='auto')\r\n"
    b"        ax.set_xticks(range(n_states))\r\n"
    b"        ax.set_xticklabels([s.replace('det_', '') for s in _plot_sc],\r\n"
    b"                           rotation=45, ha='right', fontsize=11)\r\n"
    b"        ax.set_yticks(range(n_rewards))\r\n"
    b"        ax.set_yticklabels(reward_metrics_to_test, fontsize=11)\r\n"
    b"        for i in range(n_rewards):\r\n"
    b"            for j in range(n_states):\r\n"
    b"                val = sr_matrix[i, j]\r\n"
    b"                color = 'white' if abs(val) > 0.5 else 'black'\r\n"
    b"                ax.text(j, i, f'{val:.2f}', ha='center', va='center',\r\n"
    b"                        fontsize=10, color=color,\r\n"
    b"                        fontweight='bold' if abs(val) > 0.7 else 'normal')\r\n"
    b"        fig.colorbar(im, ax=ax, shrink=0.8, pad=0.02)\r\n"
    b"        ax.set_title(f'State \xe2\x86\x92 Reward Correlation (Pearson r)\\n[{_plot_jid}, 5 agg. state]', fontsize=12)\r\n"
    b"\r\n"
    b"        # 4b. MI bar chart (csak _plot_sc alapj\xc3\xa1n \xc3\xbajrasz\xc3\xa1molva)\r\n"
    b"        ax = axes[1]\r\n"
    b"        mi_r1c1 = {}\r\n"
    b"        for rm in reward_metrics_to_test:\r\n"
    b"            if rm not in _plot_df.columns:\r\n"
    b"                mi_r1c1[rm] = 0.0\r\n"
    b"                continue\r\n"
    b"            total_mi = 0.0\r\n"
    b"            for sc in _plot_sc:\r\n"
    b"                sub = _plot_df[[sc, rm]].dropna()\r\n"
    b"                sub = sub[(sub[sc] != 0) | (sub[rm] != 0)]\r\n"
    b"                if len(sub) > 30:\r\n"
    b"                    r, _ = stats.pearsonr(sub[sc].values, sub[rm].values)\r\n"
    b"                    r2 = min(r**2, 0.9999)\r\n"
    b"                    total_mi += -0.5 * np.log(1 - r2)\r\n"
    b"            mi_r1c1[rm] = total_mi\r\n"
    b"        sorted_mi_items = sorted(mi_r1c1.items(), key=lambda x: -x[1])\r\n"
    b"        mi_names = [x[0] for x in sorted_mi_items]\r\n"
    b"        mi_vals  = [x[1] for x in sorted_mi_items]\r\n"
    b"        y = np.arange(len(mi_names))\r\n"
    b"        ax.barh(y, mi_vals, color='#3498db', alpha=0.8, height=0.6)\r\n"
    b"        for i, v in enumerate(mi_vals):\r\n"
    b"            ax.text(v + 0.02, i, f'{v:.2f}', va='center', fontsize=10)\r\n"
    b"        ax.set_yticks(y)\r\n"
    b"        ax.set_yticklabels(mi_names, fontsize=11)\r\n"
    b"        ax.set_xlabel('Gaussian Mutual Information (nats)', fontsize=10)\r\n"
    b"        ax.set_title(f'State \xe2\x86\x92 Reward: Total MI\\n[{_plot_jid}, 5 agg. state]', fontsize=12)\r\n"
    b"        ax.invert_yaxis()\r\n"
    b"        ax.grid(True, alpha=0.3, axis='x')\r\n"
    b"\r\n"
    b"        plt.tight_layout()\r\n"
    b"        fig.savefig(os.path.join(output_dir, 'reward_state_consistency.png'), dpi=200, bbox_inches='tight')\r\n"
    b"        plt.close()\r\n"
    b"        print(f\"  reward_state_consistency.png mentve ({_plot_jid}, 5 aggreg\xc3\xa1lt state)\")\r\n"
)
new4 = (
    b"    _plot_jid = 'R1C1_C'\r\n"
    b"    _plot_sc  = agg_state_cols  # csak az 5 aggreg\xc3\xa1lt\r\n"
    b"    _plot_df_all = df_valid[df_valid['junction'] == _plot_jid].copy() if 'junction' in df_valid.columns else df_valid.copy()\r\n"
    b"    if has_det_data and len(_plot_df_all) > 0:\r\n"
    b"        # Nyers metrik\xc3\xa1k + normaliz\xc3\xa1lt reward jel\xc3\xb6ltek\r\n"
    b"        raw_metrics = [m for m in ['TotalWaitingTime', 'TotalCO2', 'QueueLength',\r\n"
    b"                                    'TotalTravelTime', 'HaltRatio', 'SpeedStd', 'AvgOccupancy']\r\n"
    b"                       if m in _plot_df_all.columns]\r\n"
    b"        reward_metrics_to_test = raw_metrics + reward_metrics_5\r\n"
    b"        n_rewards = len(reward_metrics_to_test)\r\n"
    b"        n_states  = len(_plot_sc)\r\n"
    b"\r\n"
    b"        # M\xc3\xb3dok csoportos\xc3\xadt\xc3\xa1sa\r\n"
    b"        _sm_order  = ['random', 'mixed', 'actuated']\r\n"
    b"        _sm_colors = {'random': '#e74c3c', 'mixed': '#f39c12', 'actuated': '#2980b9'}\r\n"
    b"        _sm_titles = {'random': 'Random (\xcf\xb5=1.0)', 'mixed': f'Mixed (\xcf\xb5={MIXED_EPSILON})', 'actuated': 'Actuated (\xcf\xb5=0.0)'}\r\n"
    b"        def _mg_s(cm): return 'actuated' if cm == 'actuated' else ('mixed' if str(cm).startswith('mixed') else 'random')\r\n"
    b"        if 'mode_group' not in _plot_df_all.columns:\r\n"
    b"            _plot_df_all['mode_group'] = _plot_df_all['control_mode'].apply(_mg_s)\r\n"
    b"        present_sm = [m for m in _sm_order if m in _plot_df_all['mode_group'].values]\r\n"
    b"        n_sm = max(len(present_sm), 1)\r\n"
    b"\r\n"
    b"        fig, axes_sc = plt.subplots(n_sm, 2,\r\n"
    b"                                    figsize=(14, max(5, n_rewards * 0.75) * n_sm),\r\n"
    b"                                    gridspec_kw={'width_ratios': [1.2, 1]})\r\n"
    b"        if n_sm == 1:\r\n"
    b"            axes_sc = [axes_sc]\r\n"
    b"\r\n"
    b"        for row_sc, mg_sc in enumerate(present_sm):\r\n"
    b"            _plot_df = _plot_df_all[_plot_df_all['mode_group'] == mg_sc]\r\n"
    b"            _sm_color = _sm_colors.get(mg_sc, '#555555')\r\n"
    b"            ax_heat, ax_mi = axes_sc[row_sc]\r\n"
    b"\r\n"
    b"            # Heatmap\r\n"
    b"            sr_matrix = []\r\n"
    b"            for rm in reward_metrics_to_test:\r\n"
    b"                row_vals = []\r\n"
    b"                for sc in _plot_sc:\r\n"
    b"                    sub = _plot_df[[sc, rm]].dropna() if rm in _plot_df.columns else pd.DataFrame()\r\n"
    b"                    sub = sub[(sub[sc] != 0) | (sub[rm] != 0)] if len(sub) > 0 else sub\r\n"
    b"                    if len(sub) > 30:\r\n"
    b"                        r, _ = stats.pearsonr(sub[sc].values, sub[rm].values)\r\n"
    b"                        row_vals.append(r)\r\n"
    b"                    else:\r\n"
    b"                        row_vals.append(0.0)\r\n"
    b"                sr_matrix.append(row_vals)\r\n"
    b"            sr_matrix = np.array(sr_matrix)\r\n"
    b"            im = ax_heat.imshow(sr_matrix, cmap='RdBu_r', vmin=-1, vmax=1, aspect='auto')\r\n"
    b"            ax_heat.set_xticks(range(n_states))\r\n"
    b"            ax_heat.set_xticklabels([s.replace('det_', '') for s in _plot_sc],\r\n"
    b"                                    rotation=45, ha='right', fontsize=10)\r\n"
    b"            ax_heat.set_yticks(range(n_rewards))\r\n"
    b"            ax_heat.set_yticklabels(reward_metrics_to_test, fontsize=10)\r\n"
    b"            for i in range(n_rewards):\r\n"
    b"                for j in range(n_states):\r\n"
    b"                    val = sr_matrix[i, j]\r\n"
    b"                    color = 'white' if abs(val) > 0.5 else 'black'\r\n"
    b"                    ax_heat.text(j, i, f'{val:.2f}', ha='center', va='center',\r\n"
    b"                                fontsize=9, color=color,\r\n"
    b"                                fontweight='bold' if abs(val) > 0.7 else 'normal')\r\n"
    b"            fig.colorbar(im, ax=ax_heat, shrink=0.8, pad=0.02)\r\n"
    b"            ax_heat.set_title(\r\n"
    b"                f'{_sm_titles.get(mg_sc, mg_sc)}  (n={len(_plot_df)})\\n'\r\n"
    b"                f'State \xe2\x86\x92 Reward Correlation (Pearson r)  [{_plot_jid}]',\r\n"
    b"                fontsize=11, color=_sm_color, fontweight='bold')\r\n"
    b"\r\n"
    b"            # MI bar chart\r\n"
    b"            mi_sc = {}\r\n"
    b"            for rm in reward_metrics_to_test:\r\n"
    b"                if rm not in _plot_df.columns:\r\n"
    b"                    mi_sc[rm] = 0.0\r\n"
    b"                    continue\r\n"
    b"                total_mi = 0.0\r\n"
    b"                for sc in _plot_sc:\r\n"
    b"                    sub = _plot_df[[sc, rm]].dropna()\r\n"
    b"                    sub = sub[(sub[sc] != 0) | (sub[rm] != 0)]\r\n"
    b"                    if len(sub) > 30:\r\n"
    b"                        r, _ = stats.pearsonr(sub[sc].values, sub[rm].values)\r\n"
    b"                        r2 = min(r**2, 0.9999)\r\n"
    b"                        total_mi += -0.5 * np.log(1 - r2)\r\n"
    b"                mi_sc[rm] = total_mi\r\n"
    b"            sorted_mi = sorted(mi_sc.items(), key=lambda x: -x[1])\r\n"
    b"            mi_names = [x[0] for x in sorted_mi]\r\n"
    b"            mi_vals  = [x[1] for x in sorted_mi]\r\n"
    b"            y = np.arange(len(mi_names))\r\n"
    b"            ax_mi.barh(y, mi_vals, color=_sm_color, alpha=0.80, height=0.6)\r\n"
    b"            for i, v in enumerate(mi_vals):\r\n"
    b"                ax_mi.text(v + 0.02, i, f'{v:.2f}', va='center', fontsize=9)\r\n"
    b"            ax_mi.set_yticks(y)\r\n"
    b"            ax_mi.set_yticklabels(mi_names, fontsize=10)\r\n"
    b"            ax_mi.set_xlabel('Gaussian Mutual Information (nats)', fontsize=10)\r\n"
    b"            ax_mi.set_title(\r\n"
    b"                f'{_sm_titles.get(mg_sc, mg_sc)}\\nState \xe2\x86\x92 Reward: Total MI  [{_plot_jid}]',\r\n"
    b"                fontsize=11, color=_sm_color, fontweight='bold')\r\n"
    b"            ax_mi.invert_yaxis()\r\n"
    b"            ax_mi.grid(True, alpha=0.3, axis='x')\r\n"
    b"\r\n"
    b"        fig.suptitle(\r\n"
    b"            f'State \xe2\x86\x94 Reward Konzisztencia  [{_plot_jid}, {len(present_sm)} m\xc3\xb3d]',\r\n"
    b"            fontsize=14, fontweight='bold', y=1.01)\r\n"
    b"        plt.tight_layout()\r\n"
    b"        fig.savefig(os.path.join(output_dir, 'reward_state_consistency.png'), dpi=200, bbox_inches='tight')\r\n"
    b"        plt.close()\r\n"
    b"        print(f\"  reward_state_consistency.png mentve ({_plot_jid}, {len(present_sm)} m\xc3\xb3d)\")\r\n"
)

if old4 in raw:
    raw = raw.replace(old4, new4, 1); changes.append("Ábra4:OK")
elif b"present_sm" in raw:
    changes.append("Ábra4:SKIP")
else:
    sys.exit("FAIL Ábra4")

print("Changes:", changes)
with open('metric_collection_per_junction.py', 'wb') as f:
    f.write(raw)
print("DONE")
