detector_file: /app/data/detectors.add.xml
env_kwargs:
  delta_time: 5
  reward_weights:
    co2: 1.0
    time: 1.0
hyperparams:
  batch_size: 32
  buffer_size: 10000
  es_enabled: true
  es_min_delta: 0.01
  es_patience: 20
  exploration_fraction: 0.85
  gamma: 0.99
  gradient_steps: 1
  layer_size: 64
  learning_rate: 0.0001
  num_layers: 2
  train_freq: 4
logic_file: /app/data/traffic_lights.json
n_envs: 1
net_file: /app/data/mega_catalogue_v2.net.xml
project_name: sumo-rl-single
total_timesteps: 100000
wandb_api_key: ''
